name: Tests
on: [push,pull_request]
jobs:
  unit:
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        timeout-minutes: 2
      - run: npm test
        timeout-minutes: 1
        env:
          CI: true

  e2e:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_MONGO_URI: ${{ secrets.CYPRESS_MONGO_URI }}
          CYPRESS_API_BASE_URL: ${{ secrets.CYPRESS_API_BASE_URL }}
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
        with:
          start: npm start

