name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: cypress-io/github-action@v1
        env:
          NODE_ENV: test
          MONGO_DB: heroku_1wcllx6h
          MONGO_URI: mongodb://heroku_1wcllx6h:drer4pnkrehugbn7hrvr11hlge@ds039404.mlab.com:39404/heroku_1wcllx6h
          CYPRESS_API_BASE_URL: https://still-badlands-49750.herokuapp.com
          API_BASE_URL: https://still-badlands-49750.herokuapp.com
        with:
          start: npm start

