name: Cypress tests
on: [push,pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: cypress-io/github-action@v1
        env:
          CYPRESS_MONGO_URI: mongodb://heroku_1wcllx6h:drer4pnkrehugbn7hrvr11hlge@ds039404.mlab.com:39404/heroku_1wcllx6h
          CYPRESS_API_BASE_URL: still-badlands-49750.herokuapp.com/graphql
          REACT_APP_API_BASE_URL: still-badlands-49750.herokuapp.com/graphql
        with:
          start: npm start

